name = "shovel-blog"
main = "dist/app.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = ""

# Static assets served directly by Cloudflare under /assets/ path
[assets]
directory = "dist/assets/"
binding = "ASSETS"

# R2 for assets (if needed)
# [[r2_buckets]]
# binding = "ASSETS"
# bucket_name = "shovel-blog-assets"